---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install epel-release -y
        - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-7-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install epel-release -y
        - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: centos-68
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.8
      privileged: true
      provision_command:
        - yum install epel-release -y
        - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-69
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum install epel-release -y
        - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-69-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum install epel-release -y
        - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

suites:
  - name: redis
    run_list:
        - redis-omnibus
    attributes:
      redis-omnibus:
        servers:
          server:
            port: 6379
            maxmemory: "333mb"
          sessions:
            port: 5001
            maxmemory: "128mb"
    verifier:
      inspec_tests:
        - tests/redis.rb
